name: HACS Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hacs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: HACS Action
        # Pin to a released version of the action
        uses: hacs/action@22.5.0
        with:
          # The category of your repository in HACS: 
          #   for custom integrations use "integration"
          category: integration

          # The full GitHub repo name (owner/repo)
          repository: nnielzz/HA_Burgernet

          # Whether to post a comment on PRs with the check results
          comment: true

          # A space-separated list of checks to ignore (optional)
          # ignore: 

          # GitHub token (defaults to ${{ github.token }}; only override if you need a PAT)
          # github_token: ${{ secrets.GITHUB_TOKEN }}
